services:
  chat-rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rota-facil-rabbitmq
    ports:
      - "5672:5672"   # Porta de dados (AMQP)
      - "15672:15672" # Porta do Painel de Controle (Browser)
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - chat-rabbitmq-data:/var/lib/rabbitmq

  chat-database:
    image: postgres:16
    container_name: chat-database

    environment:
      POSTGRES_DB: ${CHAT_DATASOURCE_NAME}
      POSTGRES_USER: ${DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - chat-db-data:/var/lib/postgresql/data

volumes:
  auth-db-data: