services:
  chat-rabbitmq:
    image: rabbitmq:3.13-management
    container_name: chat-rabbitmq
    ports:
      - "5672:5672" # Porta de dados (AMQP)
      - "15672:15672" # Porta do Painel de Controle (Browser)
    environment:
      RABBITMQ_DEFAULT_USER: rota-facil
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - chat-rabbitmq-data:/var/lib/rabbitmq

  chat-database:
    image: postgres:16
    container_name: chat-database

    environment:
      POSTGRES_DB: chat_database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin

    ports:
      - "5432:5432"

    volumes:
      - chat-db-data:/var/lib/postgresql/data

volumes:
  chat-db-data:
  chat-rabbitmq-data:
