spring.application.name=Chat-Rooms
server.address=8080

# DATABASE
spring.datasource.url=${DATASOURCE_URL:jdbc:postgresql://localhost:5432/chat_database}
spring.datasource.username=${DATASOURCE_USERNAME:user}
spring.datasource.password=${DATASOURCE_PASSWORD:admin}

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# RABBITMQ
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:rota-facil}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:admin}